language: C
sudo: false

branches:
  only:
  - master
  - non_vlan

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get install -y libnuma-dev
  - sudo apt-get install -y linux-modules-4.15.0-1028-gcp linux-headers-$(uname -r)

script: ./boot.sh || travis_terminate 1;
