language: C
sudo: false

branches:
  only:
  - master

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get install -y libnuma-dev
  - sudo apt-get install linux-modules-4.15.0-1028-gcp

script: ./install.sh